
import "./globals.css";
import { Roboto } from 'next/font/google';

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Include the weight property (e.g., "400" for regular Roboto)
const roboto = Roboto({
  subsets: ['latin'],
  weight: ["400", "700"], // Add both regular and bold weights
});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        {children}
      </body>
    </html>
  );
}
